# 1. Problem Statement

Mumbai is one of largest and busiest city in India. Thousands of non native people who come to visit Mumbai and even the natives of Mumbai often face the problem of finding the best restaurants for their needs. They don’t have the access to all the data for all the restaurants, and even if they have it , it is too much for them to analyse.

People need a tool which can help them to select the restaurant which best fits their interests, as per the the cost, location, type, ratings, etc.

# 2. Data Description

<b> Additional_outlet_count: </b> It tells the number of additional outels of the restaurant available in the city

<b> Call: </b> It shows whether the restaurant takes order through calls or not

<b> Cost_for_two: </b> It shows the average food cost for two people

<b> Cuisines: </b> Type of food options (Italian, Mexican, Indian, etc)

<b> Delivery_Time_min_order: </b> Time for delivery, if applicable

<b> Features: </b> Extra facilities available at the restaurant, if applicable

<b> Home_Delivery: </b> It shows whether the restaurant provides home delivery or not

<b> Operational_hours: </b> Timings for the restaurant

<b> Rating_votes: </b> Total ratings of the restaurant

<b> Restaurant_Location: </b> Location where the restaurant is situated

<b> Restaurant_Name: </b> Name of the restaurant

<b> Restaurant_Type: </b> Type of the restaurant (Quick bite, family, etc)

<b> View_Menu: </b> Whether food menu is available outside the restaurant or not

# 3. Working Methodology

<ul>
    <li> Obtain all the open data about restaurant from Internet </li>
    <li> Clean and organise the data, and remove irrelevant information </li>
    <li> Filter out all the locations from the data, where restaurants are present </li>
    <li> Use geolocator api to find the latitude and longitude of the given areas </li>
    <li> Use foursquare api to obtain all the data in the above locations</li>
    <li> Merge both the data to obtain the restaurants in the area with their co-ordinates, ignore the data with missing information </li>
    <li> Use clustering and Gaussian method to approximate the ranges for locations and restaurants </li>
    <li> Provie recommendations for each category </li>
</ul>

# 4. Results

### Choosing restaurant based on popularity

In [50]:
num_top_venues = 5

for hood in mumbai_grouped['Location']:
    print("----"+hood+"----")
    temp = mumbai_grouped[mumbai_grouped['Location'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Andheri West----
               venue  freq
0  Indian Restaurant  0.35
1                Pub  0.12
2        Coffee Shop  0.12
3               Café  0.12
4          Nightclub  0.06


----Bandra West----
                venue  freq
0   Indian Restaurant  0.14
1                Café  0.08
2  Chinese Restaurant  0.07
3              Bakery  0.05
4                 Bar  0.05


----Borivali West----
                           venue  freq
0             Chinese Restaurant  0.18
1              Indian Restaurant  0.12
2  Vegetarian / Vegan Restaurant  0.12
3                 Ice Cream Shop  0.06
4        South Indian Restaurant  0.06


----Chembur----
                           venue  freq
0              Indian Restaurant  0.28
1  Vegetarian / Vegan Restaurant  0.08
2                            Bar  0.08
3                           Café  0.08
4                    Snack Place  0.04


----Kalyan----
                venue  freq
0                Café  0.19
1               Beach  0.12
2         Bus Station  0.06
3  Frozen Yogurt Shop  0.06
4         Pizza Place  0.06


----Kandivali West----
               venue  freq
0             Bakery  0.18
1        Snack Place  0.18
2       Dessert Shop  0.09
3                Gym  0.09
4  Indian Restaurant  0.09


----Malad West----
                  venue  freq
0           Snack Place  0.25
1                Garden  0.25
2           Men's Store  0.25
3  Fast Food Restaurant  0.25
4                Arcade  0.00


----Mira Road----
                venue  freq
0   Indian Restaurant  0.10
1         Coffee Shop  0.10
2  Italian Restaurant  0.10
3                 Spa  0.10
4               Hotel  0.05


----Powai----
                venue  freq
0   Indian Restaurant  0.13
1  Chinese Restaurant  0.05
2                 Bar  0.05
3      Ice Cream Shop  0.05
4          Restaurant  0.05


----Thane West----
                venue  freq
0        Concert Hall  0.25
1   Indian Restaurant  0.25
2               Diner  0.25
3  Chinese Restaurant  0.25
4              Arcade  0.00

### Choosing restaurant based on home delivery

In [54]:
res_data.groupby('Home_Delivery').count()

,Restaurant_Name,Restaurant_Location,Cuisines,Call,Cost_for_two(Rs.),Rating,Votes,Score
Home_Delivery,,,,,,,,
False,4021,4021,4020,4021,4021,4021,4021,4021
True,2302,2302,2302,2302,2302,2302,2302,2302

### Choosing restaurant based on Cost for two

In [80]:
res_data.groupby('Cost_for_two(Rs.)').count().reset_index()

,Cost_for_two(Rs.),Restaurant_Name,Restaurant_Location,Cuisines,Call,Home_Delivery,Rating,Votes,Score
0,50,1,1,1,1,1,1,1,1
1,100,72,72,72,72,72,72,72,72
2,120,3,3,3,3,3,3,3,3
3,150,157,157,157,157,157,157,157,157
4,180,1,1,1,1,1,1,1,1
5,200,350,350,350,350,350,350,350,350
6,230,1,1,1,1,1,1,1,1
7,249,1,1,1,1,1,1,1,1
8,250,250,250,250,250,250,250,250,250
9,280,1,1,1,1,1,1,1,1
10,300,605,605,605,605,605,605,605,605
11,350,330,330,330,330,330,330,330,330
12,398,1,1,1,1,1,1,1,1
13,400,665,665,664,665,665,665,665,665
14,450,324,324,324,324,324,324,324,324
15,470,1,1,1,1,1,1,1,1
16,480,1,1,1,1,1,1,1,1
17,500,900,900,900,900,900,900,900,900
18,505,1,1,1,1,1,1,1,1
19,520,1,1,1,1,1,1,1,1
20,550,285,285,285,285,285,285,285,285
21,600,555,555,555,555,555,555,555,555
22,650,158,158,158,158,158,158,158,158
23,700,287,287,287,287,287,287,287,287
24,750,78,78,78,78,78,78,78,78
25,800,239,239,239,239,239,239,239,239
26,850,43,43,43,43,43,43,43,43
27,900,83,83,83,83,83,83,83,83
28,950,18,18,18,18,18,18,18,18
29,990,1,1,1,1,1,1,1,1
30,1000,208,208,208,208,208,208,208,208
31,1050,2,2,2,2,2,2,2,2
32,1100,41,41,41,41,41,41,41,41
33,1150,4,4,4,4,4,4,4,4
34,1180,1,1,1,1,1,1,1,1
35,1200,135,135,135,135,135,135,135,135
36,1250,1,1,1,1,1,1,1,1
37,1300,36,36,36,36,36,36,36,36
38,1350,1,1,1,1,1,1,1,1
39,1400,45,45,45,45,45,45,45,45
40,1450,1,1,1,1,1,1,1,1
41,1500,108,108,108,108,108,108,108,108
42,1550,1,1,1,1,1,1,1,1
43,1600,31,31,31,31,31,31,31,31
44,1650,3,3,3,3,3,3,3,3
45,1700,18,18,18,18,18,18,18,18
46,1800,27,27,27,27,27,27,27,27
47,1850,2,2,2,2,2,2,2,2
48,1900,5,5,5,5,5,5,5,5
49,2000,50,50,50,50,50,50,50,50
50,2100,5,5,5,5,5,5,5,5
51,2200,17,17,17,17,17,17,17,17
52,2300,5,5,5,5,5,5,5,5
53,2400,2,2,2,2,2,2,2,2
54,2500,34,34,34,34,34,34,34,34
55,2600,3,3,3,3,3,3,3,3
56,2700,4,4,4,4,4,4,4,4
57,2800,3,3,3,3,3,3,3,3
58,3000,35,35,35,35,35,35,35,35
59,3200,1,1,1,1,1,1,1,1
60,3300,2,2,2,2,2,2,2,2
61,3500,16,16,16,16,16,16,16,16
62,3700,1,1,1,1,1,1,1,1
63,3800,1,1,1,1,1,1,1,1
64,4000,21,21,21,21,21,21,21,21
65,4050,1,1,1,1,1,1,1,1
66,4200,3,3,3,3,3,3,3,3
67,4500,13,13,13,13,13,13,13,13
68,5000,13,13,13,13,13,13,13,13
69,5500,3,3,3,3,3,3,3,3
70,6000,2,2,2,2,2,2,2,2
71,6500,2,2,2,2,2,2,2,2
72,8000,1,1,1,1,1,1,1,1
73,10000,1,1,1,1,1,1,1,1
74,30000,1,1,1,1,1,1,1,1

#### Choosing restaurant based on ratings

In [82]:
res_data.groupby('Rating').count().reset_index()

,Rating,Restaurant_Name,Restaurant_Location,Cuisines,Call,Home_Delivery,Cost_for_two(Rs.),Votes,Score
0,2.0,3,3,3,3,3,3,3,3
1,2.1,3,3,3,3,3,3,3,3
2,2.2,2,2,2,2,2,2,2,2
3,2.3,3,3,3,3,3,3,3,3
4,2.4,6,6,6,6,6,6,6,6
5,2.5,13,13,13,13,13,13,13,13
6,2.6,30,30,30,30,30,30,30,30
7,2.7,56,56,56,56,56,56,56,56
8,2.8,96,96,96,96,96,96,96,96
9,2.9,122,122,122,122,122,122,122,122
10,3.0,114,114,114,114,114,114,114,114
11,3.1,175,175,175,175,175,175,175,175
12,3.2,300,300,300,300,300,300,300,300
13,3.3,403,403,403,403,403,403,403,403
14,3.4,524,524,524,524,524,524,524,524
15,3.5,646,646,646,646,646,646,646,646
16,3.6,702,702,701,702,702,702,702,702
17,3.7,731,731,731,731,731,731,731,731
18,3.8,610,610,610,610,610,610,610,610
19,3.9,516,516,516,516,516,516,516,516
20,4.0,401,401,401,401,401,401,401,401
21,4.1,290,290,290,290,290,290,290,290
22,4.2,201,201,201,201,201,201,201,201
23,4.3,150,150,150,150,150,150,150,150
24,4.4,94,94,94,94,94,94,94,94
25,4.5,68,68,68,68,68,68,68,68
26,4.6,28,28,28,28,28,28,28,28
27,4.7,18,18,18,18,18,18,18,18
28,4.8,11,11,11,11,11,11,11,11
29,4.9,7,7,7,7,7,7,7,7

In [84]:
res_data.groupby('Restaurant_Location').count().reset_index()

,Restaurant_Location,Restaurant_Name,Cuisines,Call,Home_Delivery,Cost_for_two(Rs.),Rating,Votes,Score
0,4 Bungalows,32,32,32,32,32,32,32,32
1,Airoli,68,68,68,68,68,68,68,68
2,Alibaug,7,7,7,7,7,7,7,7
3,Ambernath,12,12,12,12,12,12,12,12
4,Andheri,3,3,3,3,3,3,3,3
5,Andheri East,2,2,2,2,2,2,2,2
6,Andheri West,295,295,295,295,295,295,295,295
7,Azad Nagar,22,22,22,22,22,22,22,22
8,Bandra,6,6,6,6,6,6,6,6
9,Bandra East,37,37,37,37,37,37,37,37
10,Bandra Kurla Complex,38,38,38,38,38,38,38,38
11,Bandra West,241,241,241,241,241,241,241,241
12,Bhandup,58,57,58,58,58,58,58,58
13,Bhayandar,48,48,48,48,48,48,48,48
14,Borivali East,34,34,34,34,34,34,34,34
15,Borivali West,193,193,193,193,193,193,193,193
16,Breach Candy,16,16,16,16,16,16,16,16
17,Byculla,43,43,43,43,43,43,43,43
18,CBD-Belapur,58,58,58,58,58,58,58,58
19,Chakala,89,89,89,89,89,89,89,89
20,Chandivali,26,26,26,26,26,26,26,26
21,Charni Road,37,37,37,37,37,37,37,37
22,Chembur,148,148,148,148,148,148,148,148
23,Chowpatty,31,31,31,31,31,31,31,31
24,Churchgate,24,24,24,24,24,24,24,24
25,Colaba,82,82,82,82,82,82,82,82
26,Cuffe Parade,13,13,13,13,13,13,13,13
27,Dadar,1,1,1,1,1,1,1,1
28,Dadar East,31,31,31,31,31,31,31,31
29,Dadar West,56,56,56,56,56,56,56,56
30,Dahisar East,31,31,31,31,31,31,31,31
31,Dahisar West,25,25,25,25,25,25,25,25
32,Dombivali,1,1,1,1,1,1,1,1
33,Dombivali East,125,125,125,125,125,125,125,125
34,Dombivali West,22,22,22,22,22,22,22,22
35,Fort,95,95,95,95,95,95,95,95
36,Ghansoli,22,22,22,22,22,22,22,22
37,Ghatkopar East,67,67,67,67,67,67,67,67
38,Ghatkopar West,54,54,54,54,54,54,54,54
39,Ghodbunder Road,18,18,18,18,18,18,18,18
40,Girgaum,46,46,46,46,46,46,46,46
41,Gorai,8,8,8,8,8,8,8,8
42,Goregaon East,104,104,104,104,104,104,104,104
43,Goregaon West,86,86,86,86,86,86,86,86
44,Grant Road,29,29,29,29,29,29,29,29
45,Jogeshwari,39,39,39,39,39,39,39,39
46,Juhu,100,100,100,100,100,100,100,100
47,Kalamboli,18,18,18,18,18,18,18,18
48,Kalbadevi,18,18,18,18,18,18,18,18
49,Kalwa,21,21,21,21,21,21,21,21
50,Kalyan,129,129,129,129,129,129,129,129
51,Kalyan West,1,1,1,1,1,1,1,1
52,Kamothe,37,37,37,37,37,37,37,37
53,Kandivali East,90,90,90,90,90,90,90,90
54,Kandivali West,131,131,131,131,131,131,131,131
55,Kemps Corner,22,22,22,22,22,22,22,22
56,Khar,98,98,98,98,98,98,98,98
57,Kharghar,128,128,128,128,128,128,128,128
58,Kopar Khairane,62,62,62,62,62,62,62,62
59,Kurla,53,53,53,53,53,53,53,53
60,Lower Parel,125,125,125,125,125,125,125,125
61,Mahakali,84,84,84,84,84,84,84,84
62,Mahalaxmi,18,18,18,18,18,18,18,18
63,Mahim,59,59,59,59,59,59,59,59
64,Majiwada,2,2,2,2,2,2,2,2
65,Malabar Hill,5,5,5,5,5,5,5,5
66,Malad East,35,35,35,35,35,35,35,35
67,Malad West,209,209,209,209,209,209,209,209
68,Marine Lines,30,30,30,30,30,30,30,30
69,Marol,77,77,77,77,77,77,77,77
70,Marve,17,17,17,17,17,17,17,17
71,Matunga East,53,53,53,53,53,53,53,53
72,Matunga West,11,11,11,11,11,11,11,11
73,Mazgaon,21,21,21,21,21,21,21,21
74,Mira Road,204,204,204,204,204,204,204,204
75,Mulund East,36,36,36,36,36,36,36,36
76,Mulund West,107,107,107,107,107,107,107,107
77,Mumbai Central,24,24,24,24,24,24,24,24
78,Mumbra,15,15,15,15,15,15,15,15
79,Nalasopara,40,40,40,40,40,40,40,40
80,Nariman Point,27,27,27,27,27,27,27,27
81,Nerul,74,74,74,74,74,74,74,74
82,New Panvel,40,40,40,40,40,40,40,40
83,Old Panvel,25,25,25,25,25,25,25,25
84,Panvel,1,1,1,1,1,1,1,1
85,Parel,59,59,59,59,59,59,59,59
86,Peddar Road,7,7,7,7,7,7,7,7
87,Powai,134,134,134,134,134,134,134,134
88,Prabhadevi,30,30,30,30,30,30,30,30
89,Reclamation,1,1,1,1,1,1,1,1
90,Runwal Green,5,5,5,5,5,5,5,5
91,Sakinaka,45,45,45,45,45,45,45,45
92,Sanpada,25,25,25,25,25,25,25,25
93,Santacruz East,72,72,72,72,72,72,72,72
94,Santacruz West,37,37,37,37,37,37,37,37
95,Seawoods,36,36,36,36,36,36,36,36
96,Sewri,8,8,8,8,8,8,8,8
97,Sion,56,56,56,56,56,56,56,56
98,Tardeo,30,30,30,30,30,30,30,30
99,Thane East,11,11,11,11,11,11,11,11
100,Thane West,386,386,386,386,386,386,386,386
101,Turbhe,1,1,1,1,1,1,1,1
102,Ulhasnagar,43,43,43,43,43,43,43,43
103,Vasai,111,111,111,111,111,111,111,111
104,Vashi,116,116,116,116,116,116,116,116
105,Veera Desai Area,36,36,36,36,36,36,36,36
106,Vikhroli,37,37,37,37,37,37,37,37
107,Vile Parle East,91,91,91,91,91,91,91,91
108,Vile Parle West,49,49,49,49,49,49,49,49
109,Virar,60,60,60,60,60,60,60,60
110,Wadala,17,17,17,17,17,17,17,17
111,Worli,50,50,50,50,50,50,50,50

# 5. Other Observations & Discussions 
<ul>
    <li> Most of the restaurants are located on the costal sides </li>
    <li> Most of the restaurants are quiet affordable with avg cost for two being under Rs. 1000</li>
    <li> Most of therestaurant with low prices have higher ratings with more probable number of customers</li>
    <li> There are a few restaurant which are well listed yet don't avail home delivery</li>
    <li> Chinese food and bakery seem to be the most popular Cuisines </li>
</ul>

#### A Report by <a href=https://abhishekver.github.io> Abhishek Verma </a>